# Quarkus Configuration File
quarkus.http.port=8080
quarkus.application.name=api-gateway

# Swagger UI
quarkus.swagger-ui.always-include=true

# CORS Configuration
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8081,http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.exposed-headers=Location

# OIDC Configuration
# Explicitly pointing to the running Keycloak container
quarkus.oidc.auth-server-url=http://localhost:8085/realms/quarkus
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web-app

# Admin Client Configuration
quarkus.keycloak.admin-client.server-url=http://localhost:8085
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.username=admin
quarkus.keycloak.admin-client.password=admin
quarkus.keycloak.admin-client.grant-type=password
quarkus.keycloak.admin-client.client-id=admin-cli